# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOgyJvoJv_KeYCHQZa-7FfreRjw5A-g4
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

# Fix URL cats_vs_dogs
setattr(tfds.image_classification.cats_vs_dogs, '_URL',
        "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip")

(ds_train, ds_test), info = tfds.load(
    "cats_vs_dogs",
    split=["train[:80%]", "train[80%:]"],
    as_supervised=True,
    with_info=True
)

TAMANO_IMG = 100
BATCH = 32

def preprocesar(imagen, etiqueta):
    imagen = tf.image.resize(imagen, (TAMANO_IMG, TAMANO_IMG))
    imagen = tf.image.rgb_to_grayscale(imagen)      # 1 canal
    imagen = tf.cast(imagen, tf.float32) / 255.0    # normalizar
    return imagen, etiqueta

train = ds_train.map(preprocesar, num_parallel_calls=tf.data.AUTOTUNE)\
                .shuffle(1000)\
                .batch(BATCH)\
                .prefetch(tf.data.AUTOTUNE)

val = ds_test.map(preprocesar, num_parallel_calls=tf.data.AUTOTUNE)\
             .batch(BATCH)\
             .prefetch(tf.data.AUTOTUNE)

# Modelo CNN (como el tuyo)
modelo = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(100, 100, 1)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar
hist = modelo.fit(train, validation_data=val, epochs=10)

# Guardar
modelo.save("perros-gatos-cnn.h5")

print("\n✅ Modelo guardado como perros-gatos-cnn.h5")

import matplotlib.pyplot as plt

# Tomar un ejemplo del set de validación
for img, label in val.take(1):
    img0 = img[0:1]  # 1 imagen (batch=1)
    real = int(label[0].numpy())

pred = modelo.predict(img0)[0][0]
pred_label = 1 if pred > 0.5 else 0

print("Probabilidad (perro=1):", float(pred))
print("Predicción:", "Perro" if pred_label==1 else "Gato")
print("Real:", "Perro" if real==1 else "Gato")

plt.imshow(img0[0].numpy().reshape(100,100), cmap="gray")
plt.axis("off")
plt.show()